version: "3"
services:
  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: ./services/scrapper/dockerfile.dev
      args:
        - APP=scrapper
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3001:5000"

  cover-letter-generator:
    container_name: cover-letter-generator
    build:
      context: .
      dockerfile: ./services/cover-letter-generator/dockerfile.dev
      args:
        - APP=cover-letter-generator
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3002:5000"

  job-extractor:
    container_name: job-extractor
    build:
      context: .
      dockerfile: ./services/job-extractor/dockerfile.dev
      args:
        - APP=job-extractor
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3003:5000"

  cv-extractor:
    container_name: cv-extractor
    build:
      context: .
      dockerfile: ./services/cv-extractor/dockerfile.dev
      args:
        - APP=cv-extractor
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3004:5000"

  custom-job:
    container_name: custom-job
    build:
      context: .
      dockerfile: ./services/custom-job/dockerfile.dev
      args:
        - APP=custom-job
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3005:5000"

  quiz:
    container_name: quiz
    build:
      context: .
      dockerfile: ./services/quiz/dockerfile.dev
      args:
        - APP=quiz
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3006:5000"

  cv-generator:
    container_name: cv-generator
    build:
      context: .
      dockerfile: ./services/cv-generator/dockerfile.dev
      args:
        - APP=cv-generator
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    ports:
      - "3007:5000"

networks:
  intelli-network:
    driver: bridge
