FROM python:3.8-alpine

WORKDIR /usr/src/app/

RUN apk add --no-cache gcc musl-dev libffi-dev bash git

COPY ./requirements.txt requirements.txt

COPY ./prepareAndStartDev.bash /tmp/prepareAndStartDev.bash

RUN chmod +x /tmp/prepareAndStartDev.bash

RUN python -m venv venv

RUN source venv/bin/activate

RUN apk add python3-dev build-base gcc

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN python -m nltk.downloader punkt

ARG APP

ENV APP=${APP}

COPY ./services/${APP}/ .

RUN chmod +x ./start.bash

RUN chmod +x ./startDev.bash

RUN chmod +x ./stop.bash

RUN cp -r venv /tmp/venv

RUN cp requirements.txt /tmp/requirements.txt

CMD ["bash", "/tmp/prepareAndStartDev.bash"]
