version: "3"
services:
  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=scrapper
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/scrapper/:/usr/src/app/
    ports:
      - "3001:5000"

  cover-letter-generator:
    container_name: cover-letter-generator
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=cover-letter-generator
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/cover-letter-generator/:/usr/src/app/
    ports:
      - "3002:5000"

  job-extractor:
    container_name: job-extractor
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=job-extractor
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/job-extractor/:/usr/src/app/
    ports:
      - "3003:5000"

  cv-extractor:
    container_name: cv-extractor
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=cv-extractor
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/cv-extractor/:/usr/src/app/
    ports:
      - "3004:5000"

  custom-job:
    container_name: custom-job
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=custom-job
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/custom-job/:/usr/src/app/
    ports:
      - "3005:5000"

  quiz:
    container_name: quiz
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=quiz
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/quiz/:/usr/src/app/
    ports:
      - "3006:5000"

  interview:
    container_name: interview
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=interview
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/interview/:/usr/src/app/
    ports:
      - "3007:5000"

  cv-generator:
    container_name: cv-generator
    build:
      context: .
      dockerfile: ./dockerfile.dev
      args:
        - APP=cv-generator
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/api/shared/
      - ./services/cv-generator/:/usr/src/app/
    ports:
      - "3008:5000"

networks:
  intelli-network:
    driver: bridge
