version: "3"
services:
  cover-letter:
    container_name: cover-letter-generator
    build:
      context: .
      dockerfile: .\dockerfile.dev
      args:
        - APP=cover-letter-generator
    image: clg:latest
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - intelli-network
    volumes:
      - ./shared/:/usr/src/app/shared/
      - ./services/cover-letter-generator/:/usr/src/app/
    ports:
      - "3002:5000"

networks:
  intelli-network:
    driver: bridge
    # external: true
