FROM python:3.8-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev libffi-dev bash git

COPY ./requirements.txt requirements.txt

RUN python -m venv venv

RUN source venv/bin/activate

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ARG APP

COPY ./services/${APP}/ .

RUN ls > waer.txt

RUN chmod +x ./start.bash

RUN chmod +x ./startDev.bash

RUN chmod +x ./stop.bash

CMD [ "python", "run.py"]
