FROM python:3.8-alpine

WORKDIR /usr/src/app/

ARG APP

ENV APP=${APP}

COPY ./services/${APP}/ .

RUN apk add --no-cache gcc musl-dev libffi-dev bash git python3-dev build-base entr

COPY ./services/${APP}/prepareAndStartDev.bash /tmp/prepareAndStartDev.bash

RUN chmod +x /tmp/prepareAndStartDev.bash

RUN python -m venv venv

RUN source venv/bin/activate

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN chmod +x ./start.bash

RUN chmod +x ./startDev.bash

RUN chmod +x ./stop.bash

CMD ["bash", "/tmp/prepareAndStartDev.bash"]
